version: '3'
services:

  flask_io:
    # env_file: 
    #   - .env
    # image: ${REGISTRY}y_app:${TAG}
    image: aboglion/test  # if from dockerhub
    # build: # if localy 
    #   context: ./flask_up
    #   dockerfile: Dockerfileflask_up
    restart: always
    environment:
      TEST_ENV_PASSASSWORD: mypasswornonond_B444LA
    ports:
      - "80:5000"
    networks:
      - mofet_network
    volumes:
      - ../TDC:/tdc_files
      #to see volumes :
                  #enter -> docker exec -it <container_name/ID> sh
                  #list of volumes -> df -h

networks:
  mofet_network:
    driver: bridge

