name: Run Docker Compose

on:
  push:
    branches:
      - main

env: 
  username: aboglion
  password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  docker:
    timeout-minutes: 1
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: build_container
      run: docker build -t test ./flask_app

    - name: tag_it
      run: docker tag test ${username}/test

    - name: testps
      run: docker images

    - name: Login_DockerHub
      run: echo "$password" | docker login docker.pkg.github.com -u "$username" --password-stdin 
    
    - name: bush_it
      run: docker push ${username}/test

    - name: clean_up
      if: always()
      run: docker rmi test:latest ${username}/test


      # name: Login to Docker Hub
      # uses: docker/login-action@v3
      # with:
      #   username: ${{ secrets.DOCKERHUB_USERNAME }}
      #   password: ${{ secrets.DOCKERHUB_TOKEN }}

        # name: Build and push
        # uses: docker/build-push-action@v5
        # with:
        #   push: true
        #   tags: user/app:latest

    # - name: Stop containers
    #   if: always()
    #   run: docker-compose -f "docker-compose.yaml" down
