name: Run Docker Compose

on:
  push:
    branches:
      - main
jobs:
  docker:
    timeout-minutes: 1
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # - name: Get directory
    #   run: ls

    - name: Start containers
      run: docker-compose -f "docker-compose.yaml" up -d --build

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yaml" down
