name: Run Docker Compose

on:
  push:
    branches:
      - main

env: 
  username: ${{ secrets.DOCKER_USERNAME }}
  password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  docker:
    timeout-minutes: 1
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: build_container
      run: docker build -t test ./flask_app

    - name: tag_it
      run: docker tag test ${username}/test

    - name: testps
      run: docker images

    - name: Login_DockerHub
      uses: docker/login-action@v3
      with:
        username: ${username}
        password: ${password}

    - name: bush_it
      run: docker push ${username}/test

    - name: clean_up
      if: always()
      run: docker rmi test:latest ${username}/test




        # name: Build and push
        # uses: docker/build-push-action@v5
        # with:
        #   push: true
        #   tags: user/app:latest

    # - name: Stop containers
    #   if: always()
    #   run: docker-compose -f "docker-compose.yaml" down
